# Generated by Django 4.2.23 on 2025-07-18 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_ecobags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topicos',
            fields=[
                ('id_topicos', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=40)),
                ('texto', models.TextField()),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='gestao_ecobags.usuario')),
            ],
        ),
    ]
