# Generated by Django 4.2.24 on 2025-09-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_ecobags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='realizado',
            field=models.BooleanField(default=False),
        ),
    ]
