# Generated by Django 4.2.24 on 2025-09-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_ecobags', '0002_movimentacao_realizado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nome',
            new_name='username',
        ),
    ]
