# Generated by Django 4.2.23 on 2025-07-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_ecobags', '0002_topicos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topicos',
            new_name='Topico',
        ),
        migrations.RenameField(
            model_name='topico',
            old_name='id_topicos',
            new_name='id_topico',
        ),
    ]
