# Generated by Django 4.2.23 on 2025-08-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_ecobags', '0003_rename_topicos_topico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(max_length=750)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='gestao_ecobags.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Topico',
        ),
    ]
