# Generated by Django 4.2.24 on 2025-09-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_ecobags', '0003_rename_nome_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='nota',
            field=models.IntegerField(default=0),
        ),
    ]
