# Generated by Django 4.2.23 on 2025-08-05 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_ecobags', '0004_comentario_delete_topico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=35)),
                ('sigla', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id_cidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('sigla', models.CharField(max_length=5)),
                ('fk_estado', models.ForeignKey(db_column='fk_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='gestao_ecobags.estado')),
            ],
        ),
    ]
