# Generated by Django 4.2.24 on 2025-09-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_ecobags', '0004_comentario_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='nota',
        ),
    ]
