# Generated by Django 4.2.24 on 2025-09-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_ecobags', '0005_remove_comentario_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponto',
            name='fk_usuario',
        ),
    ]
