# Generated by Django 4.2.23 on 2025-08-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_ecobags', '0005_estado_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id_ponto', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=500)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('endereco', models.CharField(max_length=255)),
                ('estoque', models.IntegerField()),
                ('fk_cidade', models.ForeignKey(db_column='fk_cidade', on_delete=django.db.models.deletion.DO_NOTHING, to='gestao_ecobags.cidade')),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='gestao_ecobags.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id_movimentacao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Entrada'), (2, 'Saída')])),
                ('quantidade', models.IntegerField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='gestao_ecobags.usuario')),
            ],
        ),
    ]
