# Generated by Django 4.2.23 on 2025-08-12 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_ecobags', '0006_ponto_movimentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fk_usuario',
            field=models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.CASCADE, to='gestao_ecobags.usuario'),
        ),
    ]
