# Generated by Django 4.2.23 on 2025-08-12 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_ecobags', '0007_alter_comentario_fk_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='fk_estado',
            field=models.ForeignKey(db_column='fk_estado', on_delete=django.db.models.deletion.CASCADE, to='gestao_ecobags.estado'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='fk_usuario',
            field=models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.CASCADE, to='gestao_ecobags.usuario'),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='fk_cidade',
            field=models.ForeignKey(db_column='fk_cidade', on_delete=django.db.models.deletion.CASCADE, to='gestao_ecobags.cidade'),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='fk_usuario',
            field=models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.CASCADE, to='gestao_ecobags.usuario'),
        ),
    ]
